# Gran Turismo 7 Car Price Tracker

# Build our metadata

Store this locally and we can update our database daily with just the json file

Car info

https://github.com/ddm999/gt7info/blob/web-new/_data/db/cars.csv

In [2]:
import urllib.request, json
import pandas as pd

Access data from the database (updated daily on available cars)

In [3]:
url = urllib.request.urlopen("https://ddm999.github.io/gt7info/data.json")
data = json.load(url)
print(data)

{'updatetimestamp': '2024-01-15 01:36:01', 'used': {'date': '24-01-15', 'cars': [{'carid': '1985', 'manufacturer': 'Pontiac', 'region': 'us', 'name': "Firebird Trans Am '78", 'credits': 110000, 'state': 'soldout', 'estimatedays': -2, 'maxestimatedays': -2, 'new': False}, {'carid': '137', 'manufacturer': 'Honda', 'region': 'jp', 'name': "Beat '91", 'credits': 15900, 'state': 'normal', 'estimatedays': 9, 'maxestimatedays': 9, 'new': True}, {'carid': '1461', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "Silvia K's Dia Selection (S13) '90", 'credits': 48200, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': True}, {'carid': '48', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "Fairlady 240ZG (HS30) '71", 'credits': 106400, 'state': 'normal', 'estimatedays': 6, 'maxestimatedays': 6, 'new': False}, {'carid': '1778', 'manufacturer': 'Volkswagen', 'region': 'de', 'name': "Volkswagen 1200 '66", 'credits': 31900, 'state': 'normal', 'estimatedays': 10, 'maxestimatedays': 10, 'new': False}, {'carid': '3422', 'manufacturer': 'BMW', 'region': 'de', 'name': "3.0 CSL '73", 'credits': 203800, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}, {'carid': '201', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "Eunos Roadster (NA) '89", 'credits': 30700, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': False}, {'carid': '3454', 'manufacturer': 'BMW', 'region': 'de', 'name': "3.0 CSL '71", 'credits': 136700, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '821', 'manufacturer': 'Honda', 'region': 'jp', 'name': "Civic Type R (EK) '97", 'credits': 55600, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}, {'carid': '829', 'manufacturer': 'Lancia', 'region': 'it', 'name': "Delta HF Integrale Evoluzione '91", 'credits': 100300, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1527', 'manufacturer': 'Fiat', 'region': 'it', 'name': "500 1.2 8V Lounge SS '08", 'credits': 13800, 'state': 'normal', 'estimatedays': 6, 'maxestimatedays': 6, 'new': False}, {'carid': '1027', 'manufacturer': 'DMC', 'region': 'us', 'name': "DeLorean S2 '04", 'credits': 427500, 'state': 'normal', 'estimatedays': 3, 'maxestimatedays': 3, 'new': False}, {'carid': '843', 'manufacturer': 'Toyota', 'region': 'jp', 'name': "Supra 3.0GT Turbo A '88", 'credits': 105500, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '334', 'manufacturer': 'Renault', 'region': 'fr', 'name': "Clio V6 24V '00", 'credits': 86100, 'state': 'normal', 'estimatedays': 7, 'maxestimatedays': 7, 'new': False}, {'carid': '379', 'manufacturer': 'Subaru', 'region': 'jp', 'name': "Impreza Coupe WRX Type R STi Ver.VI '99", 'credits': 52600, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '773', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "R32 GT-R V-spec II '94", 'credits': 179900, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '374', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "RX-7 GT-X (FC) '90", 'credits': 60200, 'state': 'normal', 'estimatedays': 7, 'maxestimatedays': 7, 'new': False}, {'carid': '301', 'manufacturer': 'Mitsubishi', 'region': 'jp', 'name': "Lancer Evolution IV GSR '96", 'credits': 46600, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1508', 'manufacturer': 'Mitsubishi', 'region': 'jp', 'name': "Lancer Evolution VI GSR T.M. SCP '99", 'credits': 178300, 'state': 'normal', 'estimatedays': 4, 'maxestimatedays': 4, 'new': False}, {'carid': '1729', 'manufacturer': 'Ford', 'region': 'us', 'name': "Mustang Mach 1 '71", 'credits': 37500, 'state': 'limited', 'estimatedays': 1, 'maxestimatedays': 1, 'new': False}, {'carid': '203', 'manufacturer': 'Honda', 'region': 'jp', 'name': "Integra Type R (DC2) '98", 'credits': 61400, 'state': 'limited', 'estimatedays': 1, 'maxestimatedays': 1, 'new': False}, {'carid': '1990', 'manufacturer': 'Lamborghini', 'region': 'it', 'name': "Diablo GT '00", 'credits': 817800, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}, {'carid': '942', 'manufacturer': 'Chevrolet', 'region': 'us', 'name': "Corvette ZR-1 (C4) '89", 'credits': 86500, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': True}, {'carid': '187', 'manufacturer': 'TVR', 'region': 'gb', 'name': "Tuscan Speed 6 '00", 'credits': 80600, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1399', 'manufacturer': 'BMW', 'region': 'de', 'name': "M3 '07", 'credits': 70000, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '3389', 'manufacturer': 'BMW', 'region': 'de', 'name': "M3 '03", 'credits': 61900, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '345', 'manufacturer': 'Toyota', 'region': 'jp', 'name': 'Sprinter Trueno 1600GT APEX (S.Shigeno Version)', 'credits': 105900, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': True}, {'carid': '3439', 'manufacturer': 'Porsche', 'region': 'de', 'name': "911 Carrera RS (993) '95", 'credits': 215200, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1578', 'manufacturer': 'Alfa Romeo', 'region': 'it', 'name': "8C Competizione '08", 'credits': 314100, 'state': 'normal', 'estimatedays': 4, 'maxestimatedays': 4, 'new': False}, {'carid': '3431', 'manufacturer': 'Porsche', 'region': 'de', 'name': "911 Carrera RS (964) '92", 'credits': 220700, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '205', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "RX-7 Spirit R Type A (FD) '02", 'credits': 221200, 'state': 'normal', 'estimatedays': 3, 'maxestimatedays': 3, 'new': False}]}, 'legend': {'date': '24-01-15', 'cars': [{'carid': '3445', 'manufacturer': 'Aston Martin', 'region': 'gb', 'name': "DB5 '64", 'credits': 929000, 'state': 'soldout', 'estimatedays': -2, 'maxestimatedays': -2, 'new': False}, {'carid': '2059', 'manufacturer': 'Chevrolet', 'region': 'us', 'name': "Corvette Stingray Racer Concept '59", 'credits': 4000000, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '3365', 'manufacturer': 'Porsche', 'region': 'de', 'name': "356 A/1500 GS GT Carrera Speedster '56", 'credits': 1500000, 'state': 'normal', 'estimatedays': 9, 'maxestimatedays': 9, 'new': False}, {'carid': '998', 'manufacturer': 'Mercedes-Benz', 'region': 'de', 'name': "Sauber Mercedes C9 '89", 'credits': 3500000, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1565', 'manufacturer': 'Ford', 'region': 'us', 'name': "Mark IV Race Car '67", 'credits': 6750000, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '954', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "R92CP '92", 'credits': 2000000, 'state': 'normal', 'estimatedays': 6, 'maxestimatedays': 6, 'new': False}, {'carid': '1935', 'manufacturer': 'Ford', 'region': 'us', 'name': "GT40 Mark I '66", 'credits': 6700000, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': False}, {'carid': '2017', 'manufacturer': 'Ferrari', 'region': 'it', 'name': "GTO '84", 'credits': 3550000, 'state': 'normal', 'estimatedays': 3, 'maxestimatedays': 3, 'new': False}, {'carid': '296', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "787B '91", 'credits': 3300000, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '665', 'manufacturer': 'Plymouth', 'region': 'us', 'name': "Superbird '70", 'credits': 529000, 'state': 'normal', 'estimatedays': 3, 'maxestimatedays': 3, 'new': False}, {'carid': '1582', 'manufacturer': 'Lamborghini', 'region': 'it', 'name': "Miura P400 Bertone Prototype '67", 'credits': 3500000, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}]}, 'dailyrace': {'date': '70-01-01', 'races': [{'courseid': 0, 'crsbase': 'No Longer Updated', 'track': 'No Longer Updated', 'logo': 'img/track/nothing.png', 'region': 'pd', 'laps': 0, 'cars': 0, 'starttype': 'You can check Twitter instead: @Nenkaai the weekend before & @Mistah_MCA at the start of a week', 'fuelcons': 0, 'tyrewear': 0, 'cartype': 'category', 'widebodyban': False, 'nitrousban': False, 'tyres': [], 'requiredtyres': [], 'bop': False, 'carsettings_specified': False, 'garagecar': False, 'carused': False, 'damage': False, 'shortcutpen': False, 'carcollisionpen': False, 'pitlanepen': False, 'time': 0, 'offset': 0, 'schedule': 'Tell your bot author to stop trying to get daily races :)'}, {'courseid': 0, 'crsbase': 'No Longer Updated', 'track': 'No Longer Updated', 'logo': 'img/track/nothing.png', 'region': 'pd', 'laps': 0, 'cars': 0, 'starttype': 'You can check Twitter instead: @Nenkaai the weekend before & @Mistah_MCA at the start of a week', 'fuelcons': 0, 'tyrewear': 0, 'cartype': 'category', 'widebodyban': False, 'nitrousban': False, 'tyres': [], 'requiredtyres': [], 'bop': False, 'carsettings_specified': False, 'garagecar': False, 'carused': False, 'damage': False, 'shortcutpen': False, 'carcollisionpen': False, 'pitlanepen': False, 'time': 0, 'offset': 0, 'schedule': 'Tell your bot author to stop trying to get daily races :)'}, {'courseid': 0, 'crsbase': 'No Longer Updated', 'track': 'No Longer Updated', 'logo': 'img/track/nothing.png', 'region': 'pd', 'laps': 0, 'cars': 0, 'starttype': 'You can check Twitter instead: @Nenkaai the weekend before & @Mistah_MCA at the start of a week', 'fuelcons': 0, 'tyrewear': 0, 'cartype': 'category', 'widebodyban': False, 'nitrousban': False, 'tyres': [], 'requiredtyres': [], 'bop': False, 'carsettings_specified': False, 'garagecar': False, 'carused': False, 'damage': False, 'shortcutpen': False, 'carcollisionpen': False, 'pitlanepen': False, 'time': 0, 'offset': 0, 'schedule': 'Tell your bot author to stop trying to get daily races :)'}]}}

In [4]:
data.keys()

dict_keys(['updatetimestamp', 'used', 'legend', 'dailyrace'])

In [5]:
print(data['used']['cars'])

[{'carid': '1985', 'manufacturer': 'Pontiac', 'region': 'us', 'name': "Firebird Trans Am '78", 'credits': 110000, 'state': 'soldout', 'estimatedays': -2, 'maxestimatedays': -2, 'new': False}, {'carid': '137', 'manufacturer': 'Honda', 'region': 'jp', 'name': "Beat '91", 'credits': 15900, 'state': 'normal', 'estimatedays': 9, 'maxestimatedays': 9, 'new': True}, {'carid': '1461', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "Silvia K's Dia Selection (S13) '90", 'credits': 48200, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': True}, {'carid': '48', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "Fairlady 240ZG (HS30) '71", 'credits': 106400, 'state': 'normal', 'estimatedays': 6, 'maxestimatedays': 6, 'new': False}, {'carid': '1778', 'manufacturer': 'Volkswagen', 'region': 'de', 'name': "Volkswagen 1200 '66", 'credits': 31900, 'state': 'normal', 'estimatedays': 10, 'maxestimatedays': 10, 'new': False}, {'carid': '3422', 'manufacturer': 'BMW', 'region': 'de', 'name': "3.0 CSL '73", 'credits': 203800, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}, {'carid': '201', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "Eunos Roadster (NA) '89", 'credits': 30700, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': False}, {'carid': '3454', 'manufacturer': 'BMW', 'region': 'de', 'name': "3.0 CSL '71", 'credits': 136700, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '821', 'manufacturer': 'Honda', 'region': 'jp', 'name': "Civic Type R (EK) '97", 'credits': 55600, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}, {'carid': '829', 'manufacturer': 'Lancia', 'region': 'it', 'name': "Delta HF Integrale Evoluzione '91", 'credits': 100300, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1527', 'manufacturer': 'Fiat', 'region': 'it', 'name': "500 1.2 8V Lounge SS '08", 'credits': 13800, 'state': 'normal', 'estimatedays': 6, 'maxestimatedays': 6, 'new': False}, {'carid': '1027', 'manufacturer': 'DMC', 'region': 'us', 'name': "DeLorean S2 '04", 'credits': 427500, 'state': 'normal', 'estimatedays': 3, 'maxestimatedays': 3, 'new': False}, {'carid': '843', 'manufacturer': 'Toyota', 'region': 'jp', 'name': "Supra 3.0GT Turbo A '88", 'credits': 105500, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '334', 'manufacturer': 'Renault', 'region': 'fr', 'name': "Clio V6 24V '00", 'credits': 86100, 'state': 'normal', 'estimatedays': 7, 'maxestimatedays': 7, 'new': False}, {'carid': '379', 'manufacturer': 'Subaru', 'region': 'jp', 'name': "Impreza Coupe WRX Type R STi Ver.VI '99", 'credits': 52600, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '773', 'manufacturer': 'Nissan', 'region': 'jp', 'name': "R32 GT-R V-spec II '94", 'credits': 179900, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '374', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "RX-7 GT-X (FC) '90", 'credits': 60200, 'state': 'normal', 'estimatedays': 7, 'maxestimatedays': 7, 'new': False}, {'carid': '301', 'manufacturer': 'Mitsubishi', 'region': 'jp', 'name': "Lancer Evolution IV GSR '96", 'credits': 46600, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1508', 'manufacturer': 'Mitsubishi', 'region': 'jp', 'name': "Lancer Evolution VI GSR T.M. SCP '99", 'credits': 178300, 'state': 'normal', 'estimatedays': 4, 'maxestimatedays': 4, 'new': False}, {'carid': '1729', 'manufacturer': 'Ford', 'region': 'us', 'name': "Mustang Mach 1 '71", 'credits': 37500, 'state': 'limited', 'estimatedays': 1, 'maxestimatedays': 1, 'new': False}, {'carid': '203', 'manufacturer': 'Honda', 'region': 'jp', 'name': "Integra Type R (DC2) '98", 'credits': 61400, 'state': 'limited', 'estimatedays': 1, 'maxestimatedays': 1, 'new': False}, {'carid': '1990', 'manufacturer': 'Lamborghini', 'region': 'it', 'name': "Diablo GT '00", 'credits': 817800, 'state': 'normal', 'estimatedays': 5, 'maxestimatedays': 5, 'new': False}, {'carid': '942', 'manufacturer': 'Chevrolet', 'region': 'us', 'name': "Corvette ZR-1 (C4) '89", 'credits': 86500, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': True}, {'carid': '187', 'manufacturer': 'TVR', 'region': 'gb', 'name': "Tuscan Speed 6 '00", 'credits': 80600, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1399', 'manufacturer': 'BMW', 'region': 'de', 'name': "M3 '07", 'credits': 70000, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '3389', 'manufacturer': 'BMW', 'region': 'de', 'name': "M3 '03", 'credits': 61900, 'state': 'limited', 'estimatedays': 2, 'maxestimatedays': 2, 'new': False}, {'carid': '345', 'manufacturer': 'Toyota', 'region': 'jp', 'name': 'Sprinter Trueno 1600GT APEX (S.Shigeno Version)', 'credits': 105900, 'state': 'normal', 'estimatedays': 8, 'maxestimatedays': 8, 'new': True}, {'carid': '3439', 'manufacturer': 'Porsche', 'region': 'de', 'name': "911 Carrera RS (993) '95", 'credits': 215200, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '1578', 'manufacturer': 'Alfa Romeo', 'region': 'it', 'name': "8C Competizione '08", 'credits': 314100, 'state': 'normal', 'estimatedays': 4, 'maxestimatedays': 4, 'new': False}, {'carid': '3431', 'manufacturer': 'Porsche', 'region': 'de', 'name': "911 Carrera RS (964) '92", 'credits': 220700, 'state': 'soldout', 'estimatedays': 0, 'maxestimatedays': 0, 'new': False}, {'carid': '205', 'manufacturer': 'Mazda', 'region': 'jp', 'name': "RX-7 Spirit R Type A (FD) '02", 'credits': 221200, 'state': 'normal', 'estimatedays': 3, 'maxestimatedays': 3, 'new': False}]

In [6]:
pd.DataFrame.from_dict(data['used']['cars'])

,carid,manufacturer,region,name,credits,state,estimatedays,maxestimatedays,new
0,1985,Pontiac,us,Firebird Trans Am '78,110000,soldout,-2,-2,False
1,137,Honda,jp,Beat '91,15900,normal,9,9,True
2,1461,Nissan,jp,Silvia K's Dia Selection (S13) '90,48200,normal,8,8,True
3,48,Nissan,jp,Fairlady 240ZG (HS30) '71,106400,normal,6,6,False
4,1778,Volkswagen,de,Volkswagen 1200 '66,31900,normal,10,10,False
5,3422,BMW,de,3.0 CSL '73,203800,normal,5,5,False
6,201,Mazda,jp,Eunos Roadster (NA) '89,30700,normal,8,8,False
7,3454,BMW,de,3.0 CSL '71,136700,limited,2,2,False
8,821,Honda,jp,Civic Type R (EK) '97,55600,normal,5,5,False
9,829,Lancia,it,Delta HF Integrale Evoluzione '91,100300,soldout,0,0,False
10,1527,Fiat,it,500 1.2 8V Lounge SS '08,13800,normal,6,6,False
11,1027,DMC,us,DeLorean S2 '04,427500,normal,3,3,False
12,843,Toyota,jp,Supra 3.0GT Turbo A '88,105500,limited,2,2,False
13,334,Renault,fr,Clio V6 24V '00,86100,normal,7,7,False
14,379,Subaru,jp,Impreza Coupe WRX Type R STi Ver.VI '99,52600,soldout,0,0,False
15,773,Nissan,jp,R32 GT-R V-spec II '94,179900,limited,2,2,False
16,374,Mazda,jp,RX-7 GT-X (FC) '90,60200,normal,7,7,False
17,301,Mitsubishi,jp,Lancer Evolution IV GSR '96,46600,soldout,0,0,False
18,1508,Mitsubishi,jp,Lancer Evolution VI GSR T.M. SCP '99,178300,normal,4,4,False
19,1729,Ford,us,Mustang Mach 1 '71,37500,limited,1,1,False
20,203,Honda,jp,Integra Type R (DC2) '98,61400,limited,1,1,False
21,1990,Lamborghini,it,Diablo GT '00,817800,normal,5,5,False
22,942,Chevrolet,us,Corvette ZR-1 (C4) '89,86500,normal,8,8,True
23,187,TVR,gb,Tuscan Speed 6 '00,80600,soldout,0,0,False
24,1399,BMW,de,M3 '07,70000,soldout,0,0,False
25,3389,BMW,de,M3 '03,61900,limited,2,2,False
26,345,Toyota,jp,Sprinter Trueno 1600GT APEX (S.Shigeno Version),105900,normal,8,8,True
27,3439,Porsche,de,911 Carrera RS (993) '95,215200,soldout,0,0,False
28,1578,Alfa Romeo,it,8C Competizione '08,314100,normal,4,4,False
29,3431,Porsche,de,911 Carrera RS (964) '92,220700,soldout,0,0,False
30,205,Mazda,jp,RX-7 Spirit R Type A (FD) '02,221200,normal,3,3,False

In [7]:
pd.DataFrame.from_dict(data['legend']['cars'])

,carid,manufacturer,region,name,credits,state,estimatedays,maxestimatedays,new
0,3445,Aston Martin,gb,DB5 '64,929000,soldout,-2,-2,False
1,2059,Chevrolet,us,Corvette Stingray Racer Concept '59,4000000,limited,2,2,False
2,3365,Porsche,de,356 A/1500 GS GT Carrera Speedster '56,1500000,normal,9,9,False
3,998,Mercedes-Benz,de,Sauber Mercedes C9 '89,3500000,soldout,0,0,False
4,1565,Ford,us,Mark IV Race Car '67,6750000,soldout,0,0,False
5,954,Nissan,jp,R92CP '92,2000000,normal,6,6,False
6,1935,Ford,us,GT40 Mark I '66,6700000,normal,8,8,False
7,2017,Ferrari,it,GTO '84,3550000,normal,3,3,False
8,296,Mazda,jp,787B '91,3300000,soldout,0,0,False
9,665,Plymouth,us,Superbird '70,529000,normal,3,3,False
10,1582,Lamborghini,it,Miura P400 Bertone Prototype '67,3500000,normal,5,5,False

Note that `maxestimatedays` is no longer used and it is set to equate `estimatedays`

Load historical daily prices from Github

"All other data folder files can also be gotten from the website: check https://www.github.com/ddm999/gt7info/tree/web-new/_data to find the filename, then replace "gt7info/_data/" with "ddm999.github.io/gt7info/data/" to get an updating download link."

In [8]:
pd.read_csv("https://raw.githubusercontent.com/ddm999/gt7info/web-new/_data/legend/24-01-15.csv")

      id       cr    state  daysremaining
0   3445   929000  soldout             -1
1   2059  4000000  limited              3
2   3365  1500000   normal             10
3    998  3500000  soldout              1
4   1565  6750000  soldout              1
5    954  2000000   normal              7
6   1935  6700000   normal              9
7   2017  3550000   normal              4
8    296  3300000  soldout              1
9    665   529000   normal              4
10  1582  3500000   normal              6

In [9]:
pd.read_csv("./github_data/legend/24-01-15.csv")

      id       cr    state  daysremaining
0   3445   929000  soldout             -1
1   2059  4000000  limited              3
2   3365  1500000   normal             10
3    998  3500000  soldout              1
4   1565  6750000  soldout              1
5    954  2000000   normal              7
6   1935  6700000   normal              9
7   2017  3550000   normal              4
8    296  3300000  soldout              1
9    665   529000   normal              4
10  1582  3500000   normal              6

Loop through each file (date) and record the past prices for legendary (and used) cars
We need a way to read the list of files on Github

In historic files, filter OUT "soldout"
Then join on ID to the main file with a new field (titled with dates) and include the price for that day

At the end, get data from Github regarding car model and manufacturer...

Save the database as a csv, plan to switch to a SQL database with `pandasql` or with `MySQL` in the future, see
* https://www.w3schools.com/python/python_mysql_getstarted.asp
* https://www.datacamp.com/tutorial/how-to-use-sql-in-pandas-using-pandasql-queries

In [9]:
pd.DataFrame.from_dict(data['legend']['cars']).to_csv("gt.csv")